version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_scroll_system
    environment:
      MYSQL_DATABASE: scroll_system
      MYSQL_USER: dev
      MYSQL_PASSWORD: high_distinction
    networks:
      - network-scroll-system
    volumes:
      - mysql_scroll_system:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  java:
    image: java_scroll_system
    container_name: java_scroll_system
    build: .
    ports:
      - "8080:8080"
    networks:
      - network-scroll-system
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_scroll_system:

networks:
  network-scroll-system:
    driver: bridge